# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
minecraft_version=26.2
loader_version=0.19.2
loom_version=1.15.+

# Dependencies
fabric_version=0.152.2+26.2
plasmid_version=0.7.2-SNAPSHOT+26.2

# Mod Properties
mod_version=1.2.3
maven_group=io.github.restioson
archives_base_name=loopdeloop
